
-- This script was generated by greek.py 

update index_entries set entry_name = replace( entry_name, '''Etumologiko>n me<ga', '&#160; &#787;&#917;&#964;&#965;&#956;&#959;&#955;&#959;&#947;&#953;&#954;&#959;&#768;&#957; &#956;&#949;&#769;&#947;&#945;' ) where entry_id = 898 and entry_name like '%''Etumologiko>n me<ga%';

update index_entries set entry_name = replace( entry_name, 'Mikropresbutiko<n', '&#924;&#953;&#954;&#961;&#959;&#960;&#961;&#949;&#963;&#946;&#965;&#964;&#953;&#954;&#959;&#769;&#957;' ) where entry_id = 2265 and entry_name like '%Mikropresbutiko<n%';

update index_entries set entry_name = replace( entry_name, 'Qhsauro<s ke<ras 
''Amalqei<as kai> kh<poi ''Adw<nidos', '&#920;&#951;&#963;&#945;&#965;&#961;&#959;&#769;&#962; &#954;&#949;&#769;&#961;&#945;&#962; &#160; &#787;&#913;&#956;&#945;&#955;&#952;&#949;&#953;&#769;&#945;&#962; &#954;&#945;&#953;&#768; &#954;&#951;&#769;&#960;&#959;&#953; &#160; &#787;&#913;&#948;&#969;&#769;&#957;&#953;&#948;&#959;&#962;' ) where entry_id = 3331 and entry_name like '%Qhsauro<s ke<ras 
''Amalqei<as kai> kh<poi ''Adw<nidos%';

update index_entries set entry_name = replace( entry_name, '$sp$$', '' );
update index_entries set entry_name = replace( entry_name, '$rm$$', '' );
update index_entries set entry_name = replace( entry_name, '$rm$', '' );
update index_entries set entry_name = replace( entry_name, '$rm', '' );
update index_entries set xref_name = replace( xref_name, '$sp$$', '' );
update index_entries set xref_name = replace( xref_name, '$rm$$', '' );
update index_entries set xref_name = replace( xref_name, '$rm$', '' );
update index_entries set xref_name = replace( xref_name, '$rm', '' );
update index_entries set entry_biblio_line = replace( entry_biblio_line, '$sp$$', '' );
update index_entries set entry_biblio_line = replace( entry_biblio_line, '$rm$$', '' );
update index_entries set entry_biblio_line = replace( entry_biblio_line, '$rm$', '' );
update index_entries set entry_biblio_line = replace( entry_biblio_line, '$rm', '' );
update index_entries set entry_biblio_block = replace( entry_biblio_block, '$sp$$', '' );
update index_entries set entry_biblio_block = replace( entry_biblio_block, '$rm$$', '' );
update index_entries set entry_biblio_block = replace( entry_biblio_block, '$rm$', '' );
update index_entries set entry_biblio_block = replace( entry_biblio_block, '$rm', '' );
update index_entry_copies set copy_notes = replace( copy_notes, 'hnegke toi nun', '&#951;&#957;&#949;&#947;&#954;&#949; &#964;&#959;&#953; &#957;&#965;&#957;' ) where entry_id = 505 and copy_notes like '%hnegke toi nun%';

update index_entry_copies set copy_notes = replace( copy_notes, 'peri> `Ierosunhs', '&#960;&#949;&#961;&#953;&#768; &#160; &#788;&#921;&#949;&#961;&#959;&#963;&#965;&#957;&#951;&#962;' ) where entry_id = 1634 and copy_notes like '%peri> `Ierosunhs%';

update index_entry_copies set copy_notes = replace( copy_notes, 'afqadhs', '&#945;&#966;&#952;&#945;&#948;&#951;&#962;' ) where entry_id = 3188 and copy_notes like '%afqadhs%';

update index_entry_copies set copy_notes = replace( copy_notes, '$sp$$', '' );
update index_entry_copies set copy_notes = replace( copy_notes, '$rm$$', '' );
update index_entry_copies set copy_notes = replace( copy_notes, '$rm$', '' );
update index_entry_copies set copy_notes = replace( copy_notes, '$rm', '' );
update index_entry_books set title_of_book = replace( title_of_book, 'Mu^qoi', '&#924;&#965;&#785;&#952;&#959;&#953;' ) where entry_id = 63 and title_of_book like '%Mu^qoi%';

update index_entry_books set title_of_book = replace( title_of_book, 'Bibl<iwn i''atrikw^n to<mos', '&#914;&#953;&#946;&#955;&#769;&#953;&#969;&#957; &#953;&#787;&#945;&#964;&#961;&#953;&#954;&#969;&#785;&#957; &#964;&#959;&#769;&#956;&#959;&#962;' ) where entry_id = 68 and title_of_book like '%Bibl<iwn i''atrikw^n to<mos%';

update index_entry_books set title_of_book = replace( title_of_book, '''Aposhmeiw<seis ei''s tou>s Sofistikou>s e''le<gcous', '&#160; &#787;&#913;&#960;&#959;&#963;&#951;&#956;&#949;&#953;&#969;&#769;&#963;&#949;&#953;&#962; &#949;&#953;&#787;&#962; &#964;&#959;&#965;&#768;&#962; &#931;&#959;&#966;&#953;&#963;&#964;&#953;&#954;&#959;&#965;&#768;&#962; &#949;&#787;&#955;&#949;&#769;&#947;&#967;&#959;&#965;&#962;' ) where entry_id = 129 and title_of_book like '%''Aposhmeiw<seis ei''s tou>s Sofistikou>s e''le<gcous%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ei''s ta> topika> ''Aristote<lous `upomnh<mata', '&#917;&#953;&#787;&#962; &#964;&#945;&#768; &#964;&#959;&#960;&#953;&#954;&#945;&#768; &#160; &#787;&#913;&#961;&#953;&#963;&#964;&#959;&#964;&#949;&#769;&#955;&#959;&#965;&#962; &#160; &#788;&#965;&#960;&#959;&#956;&#957;&#951;&#769;&#956;&#945;&#964;&#945;' ) where entry_id = 129 and title_of_book like '%Ei''s ta> topika> ''Aristote<lous `upomnh<mata%';

update index_entry_books set title_of_book = replace( title_of_book, 'Problh<mata', '&#928;&#961;&#959;&#946;&#955;&#951;&#769;&#956;&#945;&#964;&#945;' ) where entry_id = 129 and title_of_book like '%Problh<mata%';

update index_entry_books set title_of_book = replace( title_of_book, 'Zhth<mata ''Alexa<ndrou tou^ ''Afrodisiews fusika<', '&#918;&#951;&#964;&#951;&#769;&#956;&#945;&#964;&#945; &#160; &#787;&#913;&#955;&#949;&#958;&#945;&#769;&#957;&#948;&#961;&#959;&#965; &#964;&#959;&#965;&#785; &#160; &#787;&#913;&#966;&#961;&#959;&#948;&#953;&#963;&#953;&#949;&#969;&#962; &#966;&#965;&#963;&#953;&#954;&#945;&#769;' ) where entry_id = 129 and title_of_book like '%Zhth<mata ''Alexa<ndrou tou^ ''Afrodisiews fusika<%';

update index_entry_books set title_of_book = replace( title_of_book, 'Progumna<smata', '&#928;&#961;&#959;&#947;&#965;&#956;&#957;&#945;&#769;&#963;&#956;&#945;&#964;&#945;' ) where entry_id = 285 and title_of_book like '%Progumna<smata%';

update index_entry_books set title_of_book = replace( title_of_book, 'Meta<frasis tou^ Yalth^os dia> sti<cwn `hrwikw^n', '&#924;&#949;&#964;&#945;&#769;&#966;&#961;&#945;&#963;&#953;&#962; &#964;&#959;&#965;&#785; &#936;&#945;&#955;&#964;&#951;&#785;&#959;&#962; &#948;&#953;&#945;&#768; &#963;&#964;&#953;&#769;&#967;&#969;&#957; &#160; &#788;&#951;&#961;&#969;&#953;&#954;&#969;&#785;&#957;' ) where entry_id = 292 and title_of_book like '%Meta<frasis tou^ Yalth^os dia> sti<cwn `hrwikw^n%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> sunta<xews', '&#928;&#949;&#961;&#953;&#768; &#963;&#965;&#957;&#964;&#945;&#769;&#958;&#949;&#969;&#962;' ) where entry_id = 296 and title_of_book like '%Peri> sunta<xews%';

update index_entry_books set title_of_book = replace( title_of_book, '''Argonautika<', '&#160; &#787;&#913;&#961;&#947;&#959;&#957;&#945;&#965;&#964;&#953;&#954;&#945;&#769;' ) where entry_id = 297 and title_of_book like '%''Argonautika<%';

update index_entry_books set title_of_book = replace( title_of_book, 'Faino<mena', '&#934;&#945;&#953;&#957;&#959;&#769;&#956;&#949;&#957;&#945;' ) where entry_id = 305 and title_of_book like '%Faino<mena%';

update index_entry_books set title_of_book = replace( title_of_book, 'Lo<goi ''Aristei<dou', '&#923;&#959;&#769;&#947;&#959;&#953; &#160; &#787;&#913;&#961;&#953;&#963;&#964;&#949;&#953;&#769;&#948;&#959;&#965;' ) where entry_id = 316 and title_of_book like '%Lo<goi ''Aristei<dou%';

update index_entry_books set title_of_book = replace( title_of_book, 'Komoidi<ai', '&#922;&#959;&#956;&#959;&#953;&#948;&#953;&#769;&#945;&#953;' ) where entry_id = 318 and title_of_book like '%Komoidi<ai%';

update index_entry_books set title_of_book = replace( title_of_book, '''<Organon', '&#160; &#787;&#769;&#927;&#961;&#947;&#945;&#957;&#959;&#957;' ) where entry_id = 319 and title_of_book like '%''<Organon%';

update index_entry_books set title_of_book = replace( title_of_book, '''Hqika> Nikoma<ceia', '&#160; &#787;&#919;&#952;&#953;&#954;&#945;&#768; &#925;&#953;&#954;&#959;&#956;&#945;&#769;&#967;&#949;&#953;&#945;' ) where entry_id = 319 and title_of_book like '%''Hqika> Nikoma<ceia%';

update index_entry_books set title_of_book = replace( title_of_book, 'Fusikh> a''kro<asis', '&#934;&#965;&#963;&#953;&#954;&#951;&#768; &#945;&#787;&#954;&#961;&#959;&#769;&#945;&#963;&#953;&#962;' ) where entry_id = 319 and title_of_book like '%Fusikh> a''kro<asis%';

update index_entry_books set title_of_book = replace( title_of_book, 'Mhcanika<', '&#924;&#951;&#967;&#945;&#957;&#953;&#954;&#945;&#769;' ) where entry_id = 319 and title_of_book like '%Mhcanika<%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> poihtikh^s', '&#928;&#949;&#961;&#953;&#768; &#960;&#959;&#953;&#951;&#964;&#953;&#954;&#951;&#785;&#962;' ) where entry_id = 319 and title_of_book like '%Peri> poihtikh^s%';

update index_entry_books set title_of_book = replace( title_of_book, 'Problh<mata', '&#928;&#961;&#959;&#946;&#955;&#951;&#769;&#956;&#945;&#964;&#945;' ) where entry_id = 319 and title_of_book like '%Problh<mata%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ta> meta> ta> fusika<', '&#932;&#945;&#768; &#956;&#949;&#964;&#945;&#768; &#964;&#945;&#768; &#966;&#965;&#963;&#953;&#954;&#945;&#769;' ) where entry_id = 319 and title_of_book like '%Ta> meta> ta> fusika<%';

update index_entry_books set title_of_book = replace( title_of_book, '`Rhtorika<', '&#160; &#788;&#929;&#951;&#964;&#959;&#961;&#953;&#954;&#945;&#769;' ) where entry_id = 319 and title_of_book like '%`Rhtorika<%';

update index_entry_books set title_of_book = replace( title_of_book, '''Alexa<ndrou ''Ana<basis', '&#160; &#787;&#913;&#955;&#949;&#958;&#945;&#769;&#957;&#948;&#961;&#959;&#965; &#160; &#787;&#913;&#957;&#945;&#769;&#946;&#945;&#963;&#953;&#962;' ) where entry_id = 330 and title_of_book like '%''Alexa<ndrou ''Ana<basis%';

update index_entry_books set title_of_book = replace( title_of_book, 'Deipnosofistai<', '&#916;&#949;&#953;&#960;&#957;&#959;&#963;&#959;&#966;&#953;&#963;&#964;&#945;&#953;&#769;' ) where entry_id = 346 and title_of_book like '%Deipnosofistai<%';

update index_entry_books set title_of_book = replace( title_of_book, '`<Umnoi', '&#160; &#788;&#769;&#933;&#956;&#957;&#959;&#953;' ) where entry_id = 550 and title_of_book like '%`<Umnoi%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> diafora^s sta<sews', '&#928;&#949;&#961;&#953;&#768; &#948;&#953;&#945;&#966;&#959;&#961;&#945;&#785;&#962; &#963;&#964;&#945;&#769;&#963;&#949;&#969;&#962;' ) where entry_id = 720 and title_of_book like '%Peri> diafora^s sta<sews%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> tw^n prw<twn a''rcw^n', '&#928;&#949;&#961;&#953;&#768; &#964;&#969;&#785;&#957; &#960;&#961;&#969;&#769;&#964;&#969;&#957; &#945;&#787;&#961;&#967;&#969;&#785;&#957;' ) where entry_id = 721 and title_of_book like '%Peri> tw^n prw<twn a''rcw^n%';

update index_entry_books set title_of_book = replace( title_of_book, '`Rwmaikh> a''rcaiologi<a', '&#160; &#788;&#929;&#969;&#956;&#945;&#953;&#954;&#951;&#768; &#945;&#787;&#961;&#967;&#945;&#953;&#959;&#955;&#959;&#947;&#953;&#769;&#945;' ) where entry_id = 795 and title_of_book like '%`Rwmaikh> a''rcaiologi<a%';

update index_entry_books set title_of_book = replace( title_of_book, '`H th^s oi''koume<nhs perih<ghsis', '&#160; &#788;&#919; &#964;&#951;&#785;&#962; &#959;&#953;&#787;&#954;&#959;&#965;&#956;&#949;&#769;&#957;&#951;&#962; &#960;&#949;&#961;&#953;&#951;&#769;&#947;&#951;&#963;&#953;&#962;' ) where entry_id = 798 and title_of_book like '%`H th^s oi''koume<nhs perih<ghsis%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> u`<lhs i''atrikh^s', '&#928;&#949;&#961;&#953;&#768; &#965;&#788;&#769;&#955;&#951;&#962; &#953;&#787;&#945;&#964;&#961;&#953;&#954;&#951;&#785;&#962;' ) where entry_id = 803 and title_of_book like '%Peri> u`<lhs i''atrikh^s%';

update index_entry_books set title_of_book = replace( title_of_book, 'Stoicei^a', '&#931;&#964;&#959;&#953;&#967;&#949;&#953;&#785;&#945;' ) where entry_id = 905 and title_of_book like '%Stoicei^a%';

update index_entry_books set title_of_book = replace( title_of_book, 'Tragwjdi<ai', '&#932;&#961;&#945;&#947;&#969;&#802;&#948;&#953;&#769;&#945;&#953;' ) where entry_id = 910 and title_of_book like '%Tragwjdi<ai%';

update index_entry_books set title_of_book = replace( title_of_book, 'Eu''aggelikh> proparaskeu<h', '&#917;&#965;&#787;&#945;&#947;&#947;&#949;&#955;&#953;&#954;&#951;&#768; &#960;&#961;&#959;&#960;&#945;&#961;&#945;&#963;&#954;&#949;&#965;&#769;&#951;' ) where entry_id = 913 and title_of_book like '%Eu''aggelikh> proparaskeu<h%';

update index_entry_books set title_of_book = replace( title_of_book, 'Parekbolai> ei''s th>n `Omh<rou ''Ilia<da kai>
''Odu<sseian', '&#928;&#945;&#961;&#949;&#954;&#946;&#959;&#955;&#945;&#953;&#768; &#949;&#953;&#787;&#962; &#964;&#951;&#768;&#957; &#160; &#788;&#927;&#956;&#951;&#769;&#961;&#959;&#965; &#160; &#787;&#921;&#955;&#953;&#945;&#769;&#948;&#945; &#954;&#945;&#953;&#768; &#160; &#787;&#927;&#948;&#965;&#769;&#963;&#963;&#949;&#953;&#945;&#957;' ) where entry_id = 921 and title_of_book like '%Parekbolai> ei''s th>n `Omh<rou ''Ilia<da kai>
''Odu<sseian%';

update index_entry_books set title_of_book = replace( title_of_book, 'Mikropresbutiko<n', '&#924;&#953;&#954;&#961;&#959;&#960;&#961;&#949;&#963;&#946;&#965;&#964;&#953;&#954;&#959;&#769;&#957;' ) where entry_id = 1310 and title_of_book like '%Mikropresbutiko<n%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> tw^n a''riqmw^n', '&#928;&#949;&#961;&#953;&#768; &#964;&#969;&#785;&#957; &#945;&#787;&#961;&#953;&#952;&#956;&#969;&#785;&#957;' ) where entry_id = 1339 and title_of_book like '%Peri> tw^n a''riqmw^n%';

update index_entry_books set title_of_book = replace( title_of_book, '`Istori<ai', '&#160; &#788;&#921;&#963;&#964;&#959;&#961;&#953;&#769;&#945;&#953;' ) where entry_id = 1340 and title_of_book like '%`Istori<ai%';

update index_entry_books set title_of_book = replace( title_of_book, 'Lexiko<n', '&#923;&#949;&#958;&#953;&#954;&#959;&#769;&#957;' ) where entry_id = 1344 and title_of_book like '%Lexiko<n%';

update index_entry_books set title_of_book = replace( title_of_book, '''Ilia<s', '&#160; &#787;&#921;&#955;&#953;&#945;&#769;&#962;' ) where entry_id = 1385 and title_of_book like '%''Ilia<s%';

update index_entry_books set title_of_book = replace( title_of_book, '''Odu<sseia', '&#160; &#787;&#927;&#948;&#965;&#769;&#963;&#963;&#949;&#953;&#945;' ) where entry_id = 1385 and title_of_book like '%''Odu<sseia%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ei''s ta> pro<tera a''nalutika> tou^ ''Aristote<lous `upo<mnhma', '&#917;&#953;&#787;&#962; &#964;&#945;&#768; &#960;&#961;&#959;&#769;&#964;&#949;&#961;&#945; &#945;&#787;&#957;&#945;&#955;&#965;&#964;&#953;&#954;&#945;&#768; &#964;&#959;&#965;&#785; &#160; &#787;&#913;&#961;&#953;&#963;&#964;&#959;&#964;&#949;&#769;&#955;&#959;&#965;&#962; &#160; &#788;&#965;&#960;&#959;&#769;&#956;&#957;&#951;&#956;&#945;' ) where entry_id = 1814 and title_of_book like '%Ei''s ta> pro<tera a''nalutika> tou^ ''Aristote<lous `upo<mnhma%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ei''s ta> `<ustera a''nalutika> tou^ ''Aristote<lous `upo<mnhma', '&#917;&#953;&#787;&#962; &#964;&#945;&#768; &#160; &#788;&#769;&#965;&#963;&#964;&#949;&#961;&#945; &#945;&#787;&#957;&#945;&#955;&#965;&#964;&#953;&#954;&#945;&#768; &#964;&#959;&#965;&#785; &#160; &#787;&#913;&#961;&#953;&#963;&#964;&#959;&#964;&#949;&#769;&#955;&#959;&#965;&#962; &#160; &#788;&#965;&#960;&#959;&#769;&#956;&#957;&#951;&#956;&#945;' ) where entry_id = 1814 and title_of_book like '%Ei''s ta> `<ustera a''nalutika> tou^ ''Aristote<lous `upo<mnhma%';

update index_entry_books set title_of_book = replace( title_of_book, '`Ei''s to> peri> gene<sews kai> fqora^s', '&#160; &#788;&#917;&#953;&#787;&#962; &#964;&#959;&#768; &#960;&#949;&#961;&#953;&#768; &#947;&#949;&#957;&#949;&#769;&#963;&#949;&#969;&#962; &#954;&#945;&#953;&#768; &#966;&#952;&#959;&#961;&#945;&#785;&#962;' ) where entry_id = 1814 and title_of_book like '%`Ei''s to> peri> gene<sews kai> fqora^s%';

update index_entry_books set title_of_book = replace( title_of_book, '`Upo<mnhma ei''s ta> peri> Fusikh^s te<ssara prw<ta biblia tou^
''Aristote<lous', '&#160; &#788;&#933;&#960;&#959;&#769;&#956;&#957;&#951;&#956;&#945; &#949;&#953;&#787;&#962; &#964;&#945;&#768; &#960;&#949;&#961;&#953;&#768; &#934;&#965;&#963;&#953;&#954;&#951;&#785;&#962; &#964;&#949;&#769;&#963;&#963;&#945;&#961;&#945; &#960;&#961;&#969;&#769;&#964;&#945; &#946;&#953;&#946;&#955;&#953;&#945; &#964;&#959;&#965;&#785; &#160; &#787;&#913;&#961;&#953;&#963;&#964;&#959;&#964;&#949;&#769;&#955;&#959;&#965;&#962;' ) where entry_id = 1814 and title_of_book like '%`Upo<mnhma ei''s ta> peri> Fusikh^s te<ssara prw<ta biblia tou^
''Aristote<lous%';

update index_entry_books set title_of_book = replace( title_of_book, '`Upo<mnhma ei''s ta> peri> yuch^s bi<blia', '&#160; &#788;&#933;&#960;&#959;&#769;&#956;&#957;&#951;&#956;&#945; &#949;&#953;&#787;&#962; &#964;&#945;&#768; &#960;&#949;&#961;&#953;&#768; &#968;&#965;&#967;&#951;&#785;&#962; &#946;&#953;&#769;&#946;&#955;&#953;&#945;' ) where entry_id = 1814 and title_of_book like '%`Upo<mnhma ei''s ta> peri> yuch^s bi<blia%';

update index_entry_books set title_of_book = replace( title_of_book, '''Epistolai<', '&#160; &#787;&#917;&#960;&#953;&#963;&#964;&#959;&#955;&#945;&#953;&#769;' ) where entry_id = 1901 and title_of_book like '%''Epistolai<%';

update index_entry_books set title_of_book = replace( title_of_book, 'Sti<coi i''ambikoi<', '&#931;&#964;&#953;&#769;&#967;&#959;&#953; &#953;&#787;&#945;&#956;&#946;&#953;&#954;&#959;&#953;&#769;' ) where entry_id = 1901 and title_of_book like '%Sti<coi i''ambikoi<%';

update index_entry_books set title_of_book = replace( title_of_book, '`Istori<ai', '&#160; &#788;&#921;&#963;&#964;&#959;&#961;&#953;&#769;&#945;&#953;' ) where entry_id = 1901 and title_of_book like '%`Istori<ai%';

update index_entry_books set title_of_book = replace( title_of_book, '''Ioudaikh> ''arcaiologi<a', '&#160; &#787;&#921;&#959;&#965;&#948;&#945;&#953;&#954;&#951;&#768; &#160; &#787;&#945;&#961;&#967;&#945;&#953;&#959;&#955;&#959;&#947;&#953;&#769;&#945;' ) where entry_id = 1936 and title_of_book like '%''Ioudaikh> ''arcaiologi<a%';

update index_entry_books set title_of_book = replace( title_of_book, '''Ioidaikh> `alwsis', '&#160; &#787;&#921;&#959;&#953;&#948;&#945;&#953;&#954;&#951;&#768; &#160; &#788;&#945;&#955;&#969;&#963;&#953;&#962;' ) where entry_id = 1936 and title_of_book like '%''Ioidaikh> `alwsis%';

update index_entry_books set title_of_book = replace( title_of_book, '''Antikei<mena', '&#160; &#787;&#913;&#957;&#964;&#953;&#954;&#949;&#953;&#769;&#956;&#949;&#957;&#945;' ) where entry_id = 1958 and title_of_book like '%''Antikei<mena%';

update index_entry_books set title_of_book = replace( title_of_book, '''Onomastiko<n', '&#160; &#787;&#927;&#957;&#959;&#956;&#945;&#963;&#964;&#953;&#954;&#959;&#769;&#957;' ) where entry_id = 1963 and title_of_book like '%''Onomastiko<n%';

update index_entry_books set title_of_book = replace( title_of_book, 'Dia<logoi', '&#916;&#953;&#945;&#769;&#955;&#959;&#947;&#959;&#953;' ) where entry_id = 2111 and title_of_book like '%Dia<logoi%';

update index_entry_books set title_of_book = replace( title_of_book, '''Erwth<mata', '&#160; &#787;&#917;&#961;&#969;&#964;&#951;&#769;&#956;&#945;&#964;&#945;' ) where entry_id = 2148 and title_of_book like '%''Erwth<mata%';

update index_entry_books set title_of_book = replace( title_of_book, '''Alexifa<rmaka', '&#160; &#787;&#913;&#955;&#949;&#958;&#953;&#966;&#945;&#769;&#961;&#956;&#945;&#954;&#945;' ) where entry_id = 2306 and title_of_book like '%''Alexifa<rmaka%';

update index_entry_books set title_of_book = replace( title_of_book, 'Qhriaka<', '&#920;&#951;&#961;&#953;&#945;&#954;&#945;&#769;' ) where entry_id = 2306 and title_of_book like '%Qhriaka<%';

update index_entry_books set title_of_book = replace( title_of_book, '''Argonautika<', '&#160; &#787;&#913;&#961;&#947;&#959;&#957;&#945;&#965;&#964;&#953;&#954;&#945;&#769;' ) where entry_id = 2433 and title_of_book like '%''Argonautika<%';

update index_entry_books set title_of_book = replace( title_of_book, '''Olu<mpia Pu<qia Ne<mea ''<Isqmia', '&#160; &#787;&#927;&#955;&#965;&#769;&#956;&#960;&#953;&#945; &#928;&#965;&#769;&#952;&#953;&#945; &#925;&#949;&#769;&#956;&#949;&#945; &#160; &#787;&#769;&#921;&#963;&#952;&#956;&#953;&#945;' ) where entry_id = 2682 and title_of_book like '%''Olu<mpia Pu<qia Ne<mea ''<Isqmia%';

update index_entry_books set title_of_book = replace( title_of_book, '''Ennea<des', '&#160; &#787;&#917;&#957;&#957;&#949;&#945;&#769;&#948;&#949;&#962;' ) where entry_id = 2699 and title_of_book like '%''Ennea<des%';

update index_entry_books set title_of_book = replace( title_of_book, 'Para<llhla e''n bi<ois `Ellh<nwn te kai> `Rwmai<wn', '&#928;&#945;&#961;&#945;&#769;&#955;&#955;&#951;&#955;&#945; &#949;&#787;&#957; &#946;&#953;&#769;&#959;&#953;&#962; &#160; &#788;&#917;&#955;&#955;&#951;&#769;&#957;&#969;&#957; &#964;&#949; &#954;&#945;&#953;&#768; &#160; &#788;&#929;&#969;&#956;&#945;&#953;&#769;&#969;&#957;' ) where entry_id = 2700 and title_of_book like '%Para<llhla e''n bi<ois `Ellh<nwn te kai> `Rwmai<wn%';

update index_entry_books set title_of_book = replace( title_of_book, 'Stratagh<mata', '&#931;&#964;&#961;&#945;&#964;&#945;&#947;&#951;&#769;&#956;&#945;&#964;&#945;' ) where entry_id = 2704 and title_of_book like '%Stratagh<mata%';

update index_entry_books set title_of_book = replace( title_of_book, 'Sfai^ra', '&#931;&#966;&#945;&#953;&#785;&#961;&#945;' ) where entry_id = 2748 and title_of_book like '%Sfai^ra%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ghografi<a', '&#915;&#951;&#959;&#947;&#961;&#945;&#966;&#953;&#769;&#945;' ) where entry_id = 2779 and title_of_book like '%Ghografi<a%';

update index_entry_books set title_of_book = replace( title_of_book, 'Tetra<biblos', '&#932;&#949;&#964;&#961;&#945;&#769;&#946;&#953;&#946;&#955;&#959;&#962;' ) where entry_id = 2779 and title_of_book like '%Tetra<biblos%';

update index_entry_books set title_of_book = replace( title_of_book, '`Armonika<', '&#160; &#788;&#913;&#961;&#956;&#959;&#957;&#953;&#954;&#945;&#769;' ) where entry_id = 2779 and title_of_book like '%`Armonika<%';

update index_entry_books set title_of_book = replace( title_of_book, '`H mega<lh Su<ntaxis', '&#160; &#788;&#919; &#956;&#949;&#947;&#945;&#769;&#955;&#951; &#931;&#965;&#769;&#957;&#964;&#945;&#958;&#953;&#962;' ) where entry_id = 2779 and title_of_book like '%`H mega<lh Su<ntaxis%';

update index_entry_books set title_of_book = replace( title_of_book, 'Diai<resis zhthma<twn', '&#916;&#953;&#945;&#953;&#769;&#961;&#949;&#963;&#953;&#962; &#950;&#951;&#964;&#951;&#956;&#945;&#769;&#964;&#969;&#957;' ) where entry_id = 3188 and title_of_book like '%Diai<resis zhthma<twn%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> Gewgrafi<as', '&#928;&#949;&#961;&#953;&#768; &#915;&#949;&#969;&#947;&#961;&#945;&#966;&#953;&#769;&#945;&#962;' ) where entry_id = 3243 and title_of_book like '%Peri> Gewgrafi<as%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ta> tou^ Qemisti<ou `<apanta tou^t'' e''sti parafra<seis kai>
lo<goi', '&#932;&#945;&#768; &#964;&#959;&#965;&#785; &#920;&#949;&#956;&#953;&#963;&#964;&#953;&#769;&#959;&#965; &#160; &#788;&#769;&#945;&#960;&#945;&#957;&#964;&#945; &#964;&#959;&#965;&#785;&#964;&#787; &#949;&#787;&#963;&#964;&#953; &#960;&#945;&#961;&#945;&#966;&#961;&#945;&#769;&#963;&#949;&#953;&#962; &#954;&#945;&#953;&#768; &#955;&#959;&#769;&#947;&#959;&#953;' ) where entry_id = 3291 and title_of_book like '%Ta> tou^ Qemisti<ou `<apanta tou^t'' e''sti parafra<seis kai>
lo<goi%';

update index_entry_books set title_of_book = replace( title_of_book, '''Idu<llia', '&#160; &#787;&#921;&#948;&#965;&#769;&#955;&#955;&#953;&#945;' ) where entry_id = 3295 and title_of_book like '%''Idu<llia%';

update index_entry_books set title_of_book = replace( title_of_book, 'Grammatikh> ei''sagwgh<', '&#915;&#961;&#945;&#956;&#956;&#945;&#964;&#953;&#954;&#951;&#768; &#949;&#953;&#787;&#963;&#945;&#947;&#969;&#947;&#951;&#769;' ) where entry_id = 3304 and title_of_book like '%Grammatikh> ei''sagwgh<%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> mhnw^n', '&#928;&#949;&#961;&#953;&#768; &#956;&#951;&#957;&#969;&#785;&#957;' ) where entry_id = 3304 and title_of_book like '%Peri> mhnw^n%';

update index_entry_books set title_of_book = replace( title_of_book, 'Faino<mena', '&#934;&#945;&#953;&#957;&#959;&#769;&#956;&#949;&#957;&#945;' ) where entry_id = 3317 and title_of_book like '%Faino<mena%';

update index_entry_books set title_of_book = replace( title_of_book, '`H mega<lh Su<ntaxis', '&#160; &#788;&#919; &#956;&#949;&#947;&#945;&#769;&#955;&#951; &#931;&#965;&#769;&#957;&#964;&#945;&#958;&#953;&#962;' ) where entry_id = 3317 and title_of_book like '%`H mega<lh Su<ntaxis%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> futw^n ai''ti<wn', '&#928;&#949;&#961;&#953;&#768; &#966;&#965;&#964;&#969;&#785;&#957; &#945;&#953;&#787;&#964;&#953;&#769;&#969;&#957;' ) where entry_id = 3325 and title_of_book like '%Peri> futw^n ai''ti<wn%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> futw^n i`stori<as', '&#928;&#949;&#961;&#953;&#768; &#966;&#965;&#964;&#969;&#785;&#957; &#953;&#788;&#963;&#964;&#959;&#961;&#953;&#769;&#945;&#962;' ) where entry_id = 3325 and title_of_book like '%Peri> futw^n i`stori<as%';

update index_entry_books set title_of_book = replace( title_of_book, 'Ta> meta> ta> fusika<', '&#932;&#945;&#768; &#956;&#949;&#964;&#945;&#768; &#964;&#945;&#768; &#966;&#965;&#963;&#953;&#954;&#945;&#769;' ) where entry_id = 3325 and title_of_book like '%Ta> meta> ta> fusika<%';

update index_entry_books set title_of_book = replace( title_of_book, 'Atqidos dialektou eklogai', '&#913;&#964;&#952;&#953;&#948;&#959;&#962; &#948;&#953;&#945;&#955;&#949;&#954;&#964;&#959;&#965; &#949;&#954;&#955;&#959;&#947;&#945;&#953;' ) where entry_id = 3339 and title_of_book like '%Atqidos dialektou eklogai%';

update index_entry_books set title_of_book = replace( title_of_book, 'Peri> tou^ Peloponnhsiakou^ pole<mou', '&#928;&#949;&#961;&#953;&#768; &#964;&#959;&#965;&#785; &#928;&#949;&#955;&#959;&#960;&#959;&#957;&#957;&#951;&#963;&#953;&#945;&#954;&#959;&#965;&#785; &#960;&#959;&#955;&#949;&#769;&#956;&#959;&#965;' ) where entry_id = 3400 and title_of_book like '%Peri> tou^ Peloponnhsiakou^ pole<mou%';

update index_entry_books set title_of_book = replace( title_of_book, '`Ellhnika<', '&#160; &#788;&#917;&#955;&#955;&#951;&#957;&#953;&#954;&#945;&#769;' ) where entry_id = 3816 and title_of_book like '%`Ellhnika<%';

update index_entry_books set title_of_book = replace( title_of_book, '$sp$$', '' );
update index_entry_books set title_of_book = replace( title_of_book, '$rm$$', '' );
update index_entry_books set title_of_book = replace( title_of_book, '$rm$', '' );
update index_entry_books set title_of_book = replace( title_of_book, '$rm', '' );
update index_entry_books set book_biblio_line = replace( book_biblio_line, 'A''fi<konto me<n tines', '&#913;&#787;&#966;&#953;&#769;&#954;&#959;&#957;&#964;&#959; &#956;&#949;&#769;&#957; &#964;&#953;&#957;&#949;&#962;' ) where entry_id = 717 and book_biblio_line like '%A''fi<konto me<n tines%';

update index_entry_books set book_biblio_line = replace( book_biblio_line, 'Eu''aggelikh> a''po<deixis', '&#917;&#965;&#787;&#945;&#947;&#947;&#949;&#955;&#953;&#954;&#951;&#768; &#945;&#787;&#960;&#959;&#769;&#948;&#949;&#953;&#958;&#953;&#962;' ) where entry_id = 913 and book_biblio_line like '%Eu''aggelikh> a''po<deixis%';

update index_entry_books set book_biblio_line = replace( book_biblio_line, '`H tou^ `Omh<rou poi<hsis `<apasa', '&#160; &#788;&#919; &#964;&#959;&#965;&#785; &#160; &#788;&#927;&#956;&#951;&#769;&#961;&#959;&#965; &#960;&#959;&#953;&#769;&#951;&#963;&#953;&#962; &#160; &#788;&#769;&#945;&#960;&#945;&#963;&#945;' ) where entry_id = 1385 and book_biblio_line like '%`H tou^ `Omh<rou poi<hsis `<apasa%';

update index_entry_books set book_biblio_line = replace( book_biblio_line, 'Cronografi<a su<ntomos', '&#935;&#961;&#959;&#957;&#959;&#947;&#961;&#945;&#966;&#953;&#769;&#945; &#963;&#965;&#769;&#957;&#964;&#959;&#956;&#959;&#962;' ) where entry_id = 2307 and book_biblio_line like '%Cronografi<a su<ntomos%';

update index_entry_books set book_biblio_line = replace( book_biblio_line, '`H megi<sth', '&#160; &#788;&#919; &#956;&#949;&#947;&#953;&#769;&#963;&#964;&#951;' ) where entry_id = 2779 and book_biblio_line like '%`H megi<sth%';

update index_entry_books set book_biblio_line = replace( book_biblio_line, 'Diai<resis zhthma<twn', '&#916;&#953;&#945;&#953;&#769;&#961;&#949;&#963;&#953;&#962; &#950;&#951;&#964;&#951;&#956;&#945;&#769;&#964;&#969;&#957;' ) where entry_id = 3188 and book_biblio_line like '%Diai<resis zhthma<twn%';

update index_entry_books set book_biblio_line = replace( book_biblio_line, '$sp$$', '' );
update index_entry_books set book_biblio_line = replace( book_biblio_line, '$rm$$', '' );
update index_entry_books set book_biblio_line = replace( book_biblio_line, '$rm$', '' );
update index_entry_books set book_biblio_line = replace( book_biblio_line, '$rm', '' );
update index_entry_books set xref_title_of_book = replace( xref_title_of_book, '$sp$$', '' );
update index_entry_books set xref_title_of_book = replace( xref_title_of_book, '$rm$$', '' );
update index_entry_books set xref_title_of_book = replace( xref_title_of_book, '$rm$', '' );
update index_entry_books set xref_title_of_book = replace( xref_title_of_book, '$rm', '' );
update index_entry_books set copies = replace( copies, 'hnegke toi nun', '&#951;&#957;&#949;&#947;&#954;&#949; &#964;&#959;&#953; &#957;&#965;&#957;' ) where entry_id = 505 and copies like '%hnegke toi nun%';

update index_entry_books set copies = replace( copies, 'peri> `Ierosunhs', '&#960;&#949;&#961;&#953;&#768; &#160; &#788;&#921;&#949;&#961;&#959;&#963;&#965;&#957;&#951;&#962;' ) where entry_id = 1634 and copies like '%peri> `Ierosunhs%';

update index_entry_books set copies = replace( copies, 'afqadhs', '&#945;&#966;&#952;&#945;&#948;&#951;&#962;' ) where entry_id = 3188 and copies like '%afqadhs%';

update index_entry_books set copies = replace( copies, '$sp$$', '' );
update index_entry_books set copies = replace( copies, '$rm$$', '' );
update index_entry_books set copies = replace( copies, '$rm$', '' );
update index_entry_books set copies = replace( copies, '$rm', '' );
