source create_u_index_entries.sql
source create_u_index_entry_books.sql
source create_u_index_entry_copies.sql
source create_u_index_medieval_documents.sql
source create_u_index_medieval_documents_view.sql
