
-- This script was HAND-EDITED, and any changes will need to be made MANUALLY

insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Anglesey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Barnwell' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Bourne' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Bridlington' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Bristol' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Canterbury-St Gregory' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Christchurch' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Cirencester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Elsham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Guisborough' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Hartland' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Keynsham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Kirkham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Kyme' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Lanthony' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Launde' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Leicester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Markby' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Newburgh' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Newnham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Nocton Park' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Osney' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Plympton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Selborne' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Southampton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Southwick' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Taunton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Thornholm' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Thornton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Thurgarten' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Walsingham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Waltham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Wellow' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'A', 'Worksop' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Abbotsbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Abingdon' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'BA', 'Canterbury-St Augustine''s' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Bardney' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Barking' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Bath' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Battle' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Bermondsey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Burton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Bury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'BC', 'Canterbury College, Oxford' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Carisbrooke' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Castle Acre' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'BC', 'Canterbury-Christ Church' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Chertsey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Chester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Colchester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Coventry' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Crowland' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Crowland-Frieston' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'BD', 'Durham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Ely' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Evesham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Eye' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Eynsham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Faversham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Glastonbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Gloucester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Holme St Benet''s' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Hyde' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Lewes-Monkton Farleigh' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Malmesbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'BM', 'Dover-St Martin''s' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Monk Bretton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Montacute' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Norwich' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Norwich St Leonard''s' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Norwich-Yarmouth' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Pershore' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Pontefract' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'BP', 'Peterborough' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Ramsey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Reading' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Reading-Leominster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Rochester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Saffron Walden' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Sherborne' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Shrewsbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Spalding' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'St Albans' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'St Albans-Belvoir' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'St Albans-Tynemouth' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'St Neots' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Tavistock' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Tewkesbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Thetford' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Thorney' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Thorney-Deeping' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Totnes' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Westminster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Whitby' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Wilton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Winchcombe' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Winchester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Worcester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'Wymondham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'York St Mary''s' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'B', 'York St Mary''s-Rumburgh' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'C', 'Hinton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'C', 'London' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'C', 'Unidentified' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'C', 'Witham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Aylesford-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'FA', 'York Austin Friars' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Boston-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Boston-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Boston-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Boston-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Cambridge-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Cambridge-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Cambridge-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Clare-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Exeter-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Exeter-Franciscans' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Grimsby-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Grimsby-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Guildford-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Hulne-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Ipswich-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'King''s Lynn-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'King''s Lynn-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Lincoln-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Lincoln-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Lincoln-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Lincoln-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'London-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'London-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'London-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'London-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Norwich-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Norwich-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Norwich-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Oxford-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Oxford-Carmelite' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Oxford-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Oxford-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Reading-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Richmond-Observant' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Salisbury-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Southampton-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Winchester-Dominican' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'Winchester-Franciscan' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'F', 'York-Austin' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'G', 'Bullington' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'G', 'Haverholme' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'G', 'Lincoln' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'G', 'Newstead' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'G', 'North Ormsby' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'H', 'Richmond Palace' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'H', 'various' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'H', 'Westminster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'K', 'HENRY DE KIRKESTEDE' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Barlings' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Bradsole' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Hagnaby' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Newsham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Titchfield' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Tupholme' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'P', 'Welbeck' );

insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'Cambridge, Trinity College, O. 1. 59' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'London, British Library, Royal 15 A. XXXI' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'London, British Library, Royal 15 B. II' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'London, British Library, Royal 15 D. II' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'London, British Library, Royal 6 A. XIII' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'London, British Library, Sloane 3548 fol. 158' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Q', 'Oxford, Bodleian Library, Rawlinson C. 440' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'R', 'REGISTRUM ANGLIE' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Aberdeen cathedral' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Aberdeen, King''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Aberdeen, St Nicholas' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Arbroath abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Arundel' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Ashford' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Battlefield' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Beverley, Minster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Bishop Auckland' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Bosham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Clifton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Cobham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Crediton' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Darlington' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Derby' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Eton College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Fotheringhay' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Gloucester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Hemingbrough' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Heytesbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Howden' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Ipswich' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Irthlingborough' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Leicester' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Lingfield' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'London, Guildhall College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'London, Jesus Commons' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'London, St James Commons' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'London, St Martin-le-Grand' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'London, St Peter-upon-Cornhill' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'London, Whittington''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Lowthorpe' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Maidstone' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Mettingham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Norwich' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Coldingham priory' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Ottery St Mary' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Pleshey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Pontefract' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Pott Shrigley' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Crail collegiate church' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Ripon, Minster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Rotherham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Salisbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'South Malling' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Southwell, Minster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Stoke-by-Clare' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Sudbury' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Tamworth' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Tattershall' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Wallingford' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Warwick' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Westbury-on-Trym' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Westminster, St Peter' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Westminster, St Stephen' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Winchester College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Windsor' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Wingfield' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Wingham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SC', 'Wye' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Dunfermline abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Edinburgh castle' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Glasgow cathedral' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Glasgow university' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Beverley hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Bishop''s Clyst hosptial' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Blyth hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Boston guild' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Boston hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Bridport hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Bristol grammar school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Bristol hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Bristol town library' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Brough-under-Stainmore grammar school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Bury St Edmunds hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Canterbury, St James' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Canterbury, St John the Baptist' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Canterbury, St Nicholas' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Coventry guild' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Dover, Domus Dei' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Ewelme, Domus Dei' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Exeter hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Gateshead hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Hedon grammar school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Kepier hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'King''s Lynn, St John the Baptist' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'King''s Lynn, St Mary Magdalen' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Lathom almshouse' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Ledbury hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Lincoln,Holy Innocents' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Barber-Surgeons'' Co.' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London bridge chapel' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Chancery of Duchy of Lancaster' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Clarenceux King of Arms' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, College of Physicians' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Court of Arches' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Gray''s Inn' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Guildhall' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Guildhall library' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, hospital of St Bartholomew' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, hospital of St Giles' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, hospital of St Katherine' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, hospital of St Mary Elsing' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, hospital of St Mary of Bethlehem' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, hospital of St Thomas of Acre' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Inner Temple' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Inns of Court' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Lincoln''s Inn' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Mercers' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, Middle Temple' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'London, St Anthony' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Manchester grammar school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Newcastle-upon-Tyne, hospital of St Mary' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Norwich, hospital of St Mary Magdalen' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Norwich, St Giles' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Norwich town library' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Holyrood abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Holyroodhouse, Queen Mary''s library' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Pontefract almshouse' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Ripon, hospital of St John the Baptist' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Ripon, hospital of St Mary Magdalen' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Rochester bridge chapel' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Rochester cathedral' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Rome, English hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Saffron Walden almshouse' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Salisbury hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Sandwich hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Sedbergh grammar school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Sevenoaks, hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Sherburn, hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Southampton, Domus Dei' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Southwold, townsmen' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Stamford,Browne''s Hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Stamford, hospital of St Thomas & St John' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Stamford, St Giles' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Stratford-upon-Avon, guild of Holy Cross' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Thetford, hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Wainfleet grammar sch' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Wakefield bridge chap' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Westminster, hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'West Somerton hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Whitkirk hospital and school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Winchester, Holy Cross' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Winchester, St John the Baptist' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Winchester, St Mary Madgalen' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Worcester town library' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Wotton-under-Edge, school' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'Writtle hospital' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'York bridge chapel' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'York, hospital of Christ and St Mary' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'York, St Leonard' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SH', 'York, St Thomas' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Jedburgh abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Kelso abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Kinloss abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Loch Leven priory' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Melrose abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Newbattle abbey' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'SS', 'Syon' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'St Andrews cathedral priory' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'St Andrews Dominicans' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'St Andrews, St Leonard''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'St Andrew''s University' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Stirling, Chapel Royal' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'Stirling, Franciscans' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'St Mary''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'S', 'St Salvator''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Burden Hostel' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Christ''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Clare College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Corpus Christi College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Donor documents' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Gonville and Caius College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Jesus College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'King''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'King''s Hall' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Michaelhouse' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Pembroke College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Peterhouse' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Queens'' College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'St Catharine''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'St John''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'Trinity Hall' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UC', 'University' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Buildwas' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Croxden' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Hoxne' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Hyde' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Lynne' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Saffron Walden' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'X', 'Warden' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Bealieu' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Bordesley' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Buckfast' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Byland' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Coggeshall' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Dunkeswell' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Flaxley' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Ford' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Fountains' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Jervaulx' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Kirkstead' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'London' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Louth Park' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Meaux' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Netley' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Newenham' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Revesby' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Rievaulx' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Sawtry' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Stoneleigh' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Stratford Langthorne' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Swine' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Warden' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'Z', 'Waverley' );

insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'University' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'All Souls College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Balliol College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Brasenose College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Corpus Christi College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Exeter College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Lincoln College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Magdalen College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Merton College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'New College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'Oriel College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'The Queen''s College' );
insert into index_medieval_doc_groups( doc_group_type, doc_group_name ) values ( 'UO', 'University College' );

